# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'stack.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(798, 769)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("EuroRoman")
        MainWindow.setFont(font)
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        MainWindow.setStyleSheet("margin: 0 0 0 0z")
        MainWindow.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(10, 540, 781, 211))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setStyleSheet("background-color:#ffffff;")
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap("img/ewol-logo-grey.png"))
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(10, 30, 780, 510))
        self.stackedWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.stackedWidget.setStyleSheet("padding:0;\n"
"background-color: rgb(255, 255, 255);\n"
"margin:0;\n"
"color:#F0F0F0;")
        self.stackedWidget.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.stackedWidget.setObjectName("stackedWidget")
        self.uvodnaStran = QtWidgets.QWidget()
        self.uvodnaStran.setObjectName("uvodnaStran")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.uvodnaStran)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.gridLayout_10 = QtWidgets.QGridLayout()
        self.gridLayout_10.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout_10.setContentsMargins(0, 0, -1, -1)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.kolo2niprisotno = QtWidgets.QPushButton(self.uvodnaStran)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.kolo2niprisotno.setFont(font)
        self.kolo2niprisotno.setStyleSheet("background-color:#0CB1E8;\n"
"color: #ffffff;\n"
"border-radius:15%\n"
"")
        self.kolo2niprisotno.setObjectName("kolo2niprisotno")
        self.gridLayout_10.addWidget(self.kolo2niprisotno, 2, 2, 1, 1)
        self.kolo1niprisotno = QtWidgets.QPushButton(self.uvodnaStran)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.kolo1niprisotno.setFont(font)
        self.kolo1niprisotno.setStyleSheet("background-color:#0CB1E8;\n"
"color: #ffffff;\n"
"border-radius:15%\n"
"")
        self.kolo1niprisotno.setObjectName("kolo1niprisotno")
        self.gridLayout_10.addWidget(self.kolo1niprisotno, 2, 1, 1, 1)
        self.btn_sposodi = QtWidgets.QPushButton(self.uvodnaStran)
        self.btn_sposodi.setMinimumSize(QtCore.QSize(300, 70))
        self.btn_sposodi.setMaximumSize(QtCore.QSize(300, 16777215))
        font = QtGui.QFont()
        font.setFamily("Exo 2")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.btn_sposodi.setFont(font)
        self.btn_sposodi.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_sposodi.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_sposodi.setStyleSheet("background-color:#0CB1E8;\n"
"color: #ffffff;\n"
"border-radius:15%\n"
"")
        self.btn_sposodi.setFlat(False)
        self.btn_sposodi.setObjectName("btn_sposodi")
        self.gridLayout_10.addWidget(self.btn_sposodi, 0, 0, 1, 1)
        self.btn_informacije = QtWidgets.QPushButton(self.uvodnaStran)
        self.btn_informacije.setMinimumSize(QtCore.QSize(300, 70))
        self.btn_informacije.setMaximumSize(QtCore.QSize(300, 16777215))
        font = QtGui.QFont()
        font.setFamily("Exo 2")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.btn_informacije.setFont(font)
        self.btn_informacije.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_informacije.setStyleSheet("background-color:#0CB1E8;\n"
"color: #ffffff;\n"
"border-radius:15%\n"
"")
        self.btn_informacije.setFlat(False)
        self.btn_informacije.setObjectName("btn_informacije")
        self.gridLayout_10.addWidget(self.btn_informacije, 6, 0, 1, 1)
        self.kolo1prisotno = QtWidgets.QPushButton(self.uvodnaStran)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.kolo1prisotno.setFont(font)
        self.kolo1prisotno.setStyleSheet("background-color:#0CB1E8;\n"
"color: #ffffff;\n"
"border-radius:15%\n"
"")
        self.kolo1prisotno.setObjectName("kolo1prisotno")
        self.gridLayout_10.addWidget(self.kolo1prisotno, 0, 1, 1, 1)
        self.kolo2prisotno = QtWidgets.QPushButton(self.uvodnaStran)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.kolo2prisotno.setFont(font)
        self.kolo2prisotno.setStyleSheet("background-color:#0CB1E8;\n"
"color: #ffffff;\n"
"border-radius:15%\n"
"")
        self.kolo2prisotno.setObjectName("kolo2prisotno")
        self.gridLayout_10.addWidget(self.kolo2prisotno, 0, 2, 1, 1)
        self.polniKolo2 = QtWidgets.QPushButton(self.uvodnaStran)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.polniKolo2.setFont(font)
        self.polniKolo2.setStyleSheet("background-color:#0CB1E8;\n"
"color: #ffffff;\n"
"border-radius:15%\n"
"")
        self.polniKolo2.setObjectName("polniKolo2")
        self.gridLayout_10.addWidget(self.polniKolo2, 6, 2, 1, 1)
        self.polniKolo1 = QtWidgets.QPushButton(self.uvodnaStran)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.polniKolo1.setFont(font)
        self.polniKolo1.setStyleSheet("background-color:#0CB1E8;\n"
"color: #ffffff;\n"
"border-radius:15%\n"
"")
        self.polniKolo1.setObjectName("polniKolo1")
        self.gridLayout_10.addWidget(self.polniKolo1, 6, 1, 1, 1)
        self.btn_vrni = QtWidgets.QPushButton(self.uvodnaStran)
        self.btn_vrni.setMinimumSize(QtCore.QSize(300, 70))
        self.btn_vrni.setMaximumSize(QtCore.QSize(300, 16777215))
        font = QtGui.QFont()
        font.setFamily("Exo 2")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.btn_vrni.setFont(font)
        self.btn_vrni.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_vrni.setStyleSheet("background-color:#0CB1E8;\n"
"color: #ffffff;\n"
"border-radius:15%\n"
"")
        self.btn_vrni.setFlat(False)
        self.btn_vrni.setObjectName("btn_vrni")
        self.gridLayout_10.addWidget(self.btn_vrni, 2, 0, 1, 1)
        self.btn_rezerviraj = QtWidgets.QPushButton(self.uvodnaStran)
        self.btn_rezerviraj.setMinimumSize(QtCore.QSize(0, 70))
        font = QtGui.QFont()
        font.setFamily("Exo 2")
        font.setPointSize(16)
        self.btn_rezerviraj.setFont(font)
        self.btn_rezerviraj.setStyleSheet("background-color:#0CB1E8;\n"
"color: #ffffff;\n"
"border-radius:15%\n"
"")
        self.btn_rezerviraj.setObjectName("btn_rezerviraj")
        self.gridLayout_10.addWidget(self.btn_rezerviraj, 4, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_10.addItem(spacerItem, 5, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_10.addItem(spacerItem1, 1, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_10.addItem(spacerItem2, 3, 0, 1, 1)
        self.stebricek1rezerviran = QtWidgets.QPushButton(self.uvodnaStran)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.stebricek1rezerviran.setFont(font)
        self.stebricek1rezerviran.setStyleSheet("background-color:#0CB1E8;\n"
"color: #ffffff;\n"
"border-radius:15%\n"
"")
        self.stebricek1rezerviran.setObjectName("stebricek1rezerviran")
        self.gridLayout_10.addWidget(self.stebricek1rezerviran, 4, 1, 1, 1)
        self.stebricek2rezerviran = QtWidgets.QPushButton(self.uvodnaStran)
        font = QtGui.QFont()
        font.setFamily("Exo 2")
        font.setPointSize(16)
        self.stebricek2rezerviran.setFont(font)
        self.stebricek2rezerviran.setStyleSheet("background-color:#0CB1E8;\n"
"color: #ffffff;\n"
"border-radius:15%\n"
"")
        self.stebricek2rezerviran.setObjectName("stebricek2rezerviran")
        self.gridLayout_10.addWidget(self.stebricek2rezerviran, 4, 2, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout_10)
        self.stackedWidget.addWidget(self.uvodnaStran)
        self.stranSposodi = QtWidgets.QWidget()
        self.stranSposodi.setObjectName("stranSposodi")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.stranSposodi)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(self.stranSposodi)
        self.label.setMinimumSize(QtCore.QSize(0, 75))
        self.label.setMaximumSize(QtCore.QSize(500, 75))
        font = QtGui.QFont()
        font.setFamily("Exo 2 Light")
        font.setPointSize(36)
        font.setItalic(False)
        self.label.setFont(font)
        self.label.setStyleSheet("color:#828486;")
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.sposodiLayout = QtWidgets.QGridLayout()
        self.sposodiLayout.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.sposodiLayout.setHorizontalSpacing(6)
        self.sposodiLayout.setVerticalSpacing(30)
        self.sposodiLayout.setObjectName("sposodiLayout")
        self.zeroBikes = QtWidgets.QLabel(self.stranSposodi)
        self.zeroBikes.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("Exo 2 Light")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.zeroBikes.setFont(font)
        self.zeroBikes.setStyleSheet("position:absolute;\n"
"margin-bottom:0px;\n"
"background-color:#ffffff;\n"
"color: #828486;\n"
"border-radius:13%;")
        self.zeroBikes.setAlignment(QtCore.Qt.AlignCenter)
        self.zeroBikes.setObjectName("zeroBikes")
        self.sposodiLayout.addWidget(self.zeroBikes, 0, 0, 1, 1)
        self.gridLayout_2.addLayout(self.sposodiLayout, 1, 0, 1, 1)
        self.btn_nazaj0 = QtWidgets.QPushButton(self.stranSposodi)
        self.btn_nazaj0.setMinimumSize(QtCore.QSize(760, 50))
        self.btn_nazaj0.setMaximumSize(QtCore.QSize(1000, 16777215))
        font = QtGui.QFont()
        font.setFamily("Exo 2")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.btn_nazaj0.setFont(font)
        self.btn_nazaj0.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_nazaj0.setStyleSheet("background-color:#0CB1E8;\n"
"color: #ffffff;\n"
"border-radius:13%\n"
"")
        self.btn_nazaj0.setObjectName("btn_nazaj0")
        self.gridLayout_2.addWidget(self.btn_nazaj0, 3, 0, 1, 1)
        self.stackedWidget.addWidget(self.stranSposodi)
        self.stranRezerviraj = QtWidgets.QWidget()
        font = QtGui.QFont()
        font.setPointSize(32)
        self.stranRezerviraj.setFont(font)
        self.stranRezerviraj.setObjectName("stranRezerviraj")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.stranRezerviraj)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_3 = QtWidgets.QLabel(self.stranRezerviraj)
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 75))
        font = QtGui.QFont()
        font.setFamily("Exo 2 Light")
        font.setPointSize(36)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color:#828486;")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalLayout.addLayout(self.gridLayout_3)
        self.btn_nazaj2 = QtWidgets.QPushButton(self.stranRezerviraj)
        self.btn_nazaj2.setEnabled(True)
        self.btn_nazaj2.setMinimumSize(QtCore.QSize(760, 50))
        self.btn_nazaj2.setMaximumSize(QtCore.QSize(760, 30))
        font = QtGui.QFont()
        font.setFamily("Exo 2")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.btn_nazaj2.setFont(font)
        self.btn_nazaj2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_nazaj2.setStyleSheet("background-color:#0CB1E8;\n"
"color: #ffffff;\n"
"border-radius:13%;\n"
"")
        self.btn_nazaj2.setObjectName("btn_nazaj2")
        self.verticalLayout.addWidget(self.btn_nazaj2)
        spacerItem3 = QtWidgets.QSpacerItem(20, 1, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem3)
        spacerItem4 = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem4)
        self.gridLayout_7.addLayout(self.verticalLayout, 2, 0, 1, 1)
        self.stackedWidget.addWidget(self.stranRezerviraj)
        self.stranInformacije = QtWidgets.QWidget()
        self.stranInformacije.setObjectName("stranInformacije")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.stranInformacije)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.btn_nazaj1 = QtWidgets.QPushButton(self.stranInformacije)
        self.btn_nazaj1.setMinimumSize(QtCore.QSize(100, 50))
        self.btn_nazaj1.setMaximumSize(QtCore.QSize(760, 16777215))
        font = QtGui.QFont()
        font.setFamily("Exo 2")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.btn_nazaj1.setFont(font)
        self.btn_nazaj1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_nazaj1.setStyleSheet("background-color:#0CB1E8;\n"
"color: #ffffff;\n"
"border-radius:13%\n"
"")
        self.btn_nazaj1.setObjectName("btn_nazaj1")
        self.gridLayout_4.addWidget(self.btn_nazaj1, 2, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.stranInformacije)
        self.label_2.setMaximumSize(QtCore.QSize(650, 75))
        font = QtGui.QFont()
        font.setFamily("Exo 2 Light")
        font.setPointSize(36)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color:#828486;")
        self.label_2.setObjectName("label_2")
        self.gridLayout_4.addWidget(self.label_2, 0, 0, 1, 1)
        self.stackedWidget_2 = QtWidgets.QStackedWidget(self.stranInformacije)
        self.stackedWidget_2.setStyleSheet("")
        self.stackedWidget_2.setObjectName("stackedWidget_2")
        self.page_1 = QtWidgets.QWidget()
        self.page_1.setObjectName("page_1")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.page_1)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setVerticalSpacing(50)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.btn_postaja1 = QtWidgets.QPushButton(self.page_1)
        self.btn_postaja1.setMinimumSize(QtCore.QSize(0, 50))
        self.btn_postaja1.setMaximumSize(QtCore.QSize(300, 16777215))
        font = QtGui.QFont()
        font.setFamily("Exo 2")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_postaja1.setFont(font)
        self.btn_postaja1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_postaja1.setStyleSheet("background-color:#0CB1E8;\n"
"color: #ffffff;\n"
"border-radius:13%;\n"
"")
        self.btn_postaja1.setObjectName("btn_postaja1")
        self.gridLayout_5.addWidget(self.btn_postaja1, 0, 0, 1, 1)
        self.btn_postaja4 = QtWidgets.QPushButton(self.page_1)
        self.btn_postaja4.setMinimumSize(QtCore.QSize(0, 50))
        self.btn_postaja4.setMaximumSize(QtCore.QSize(300, 16777215))
        font = QtGui.QFont()
        font.setFamily("Exo 2")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_postaja4.setFont(font)
        self.btn_postaja4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_postaja4.setStyleSheet("background-color:#0CB1E8;\n"
"color: #ffffff;\n"
"border-radius:13%\n"
"")
        self.btn_postaja4.setObjectName("btn_postaja4")
        self.gridLayout_5.addWidget(self.btn_postaja4, 3, 0, 1, 1)
        self.btn_postaja3 = QtWidgets.QPushButton(self.page_1)
        self.btn_postaja3.setMinimumSize(QtCore.QSize(0, 50))
        self.btn_postaja3.setMaximumSize(QtCore.QSize(300, 16777215))
        font = QtGui.QFont()
        font.setFamily("Exo 2")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_postaja3.setFont(font)
        self.btn_postaja3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_postaja3.setStyleSheet("background-color:#0CB1E8;\n"
"color: #ffffff;\n"
"border-radius:13%\n"
"")
        self.btn_postaja3.setObjectName("btn_postaja3")
        self.gridLayout_5.addWidget(self.btn_postaja3, 2, 0, 1, 1)
        self.btn_postaja2 = QtWidgets.QPushButton(self.page_1)
        self.btn_postaja2.setMinimumSize(QtCore.QSize(0, 50))
        self.btn_postaja2.setMaximumSize(QtCore.QSize(300, 16777215))
        font = QtGui.QFont()
        font.setFamily("Exo 2")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_postaja2.setFont(font)
        self.btn_postaja2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_postaja2.setStyleSheet("background-color:#0CB1E8;\n"
"color: #ffffff;\n"
"border-radius:13%\n"
"")
        self.btn_postaja2.setObjectName("btn_postaja2")
        self.gridLayout_5.addWidget(self.btn_postaja2, 1, 0, 1, 1)
        self.verticalLayout_5.addLayout(self.gridLayout_5)
        self.verticalLayout_6.addLayout(self.verticalLayout_5)
        self.stackedWidget_2.addWidget(self.page_1)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.page_2)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.informacijeTabela1 = QtWidgets.QTableWidget(self.page_2)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.informacijeTabela1.setFont(font)
        self.informacijeTabela1.setStyleSheet("color:#828486;")
        self.informacijeTabela1.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.informacijeTabela1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.informacijeTabela1.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.informacijeTabela1.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.informacijeTabela1.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.informacijeTabela1.setAutoScrollMargin(5)
        self.informacijeTabela1.setEditTriggers(QtWidgets.QAbstractItemView.AnyKeyPressed|QtWidgets.QAbstractItemView.EditKeyPressed)
        self.informacijeTabela1.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.informacijeTabela1.setIconSize(QtCore.QSize(50, 50))
        self.informacijeTabela1.setTextElideMode(QtCore.Qt.ElideNone)
        self.informacijeTabela1.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.informacijeTabela1.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.informacijeTabela1.setShowGrid(True)
        self.informacijeTabela1.setGridStyle(QtCore.Qt.SolidLine)
        self.informacijeTabela1.setObjectName("informacijeTabela1")
        self.informacijeTabela1.setColumnCount(0)
        self.informacijeTabela1.setRowCount(0)
        self.informacijeTabela1.horizontalHeader().setVisible(False)
        self.informacijeTabela1.horizontalHeader().setDefaultSectionSize(240)
        self.informacijeTabela1.horizontalHeader().setHighlightSections(False)
        self.informacijeTabela1.horizontalHeader().setMinimumSectionSize(200)
        self.informacijeTabela1.verticalHeader().setVisible(False)
        self.informacijeTabela1.verticalHeader().setDefaultSectionSize(150)
        self.informacijeTabela1.verticalHeader().setHighlightSections(False)
        self.informacijeTabela1.verticalHeader().setMinimumSectionSize(150)
        self.gridLayout.addWidget(self.informacijeTabela1, 0, 0, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.stackedWidget_2.addWidget(self.page_2)
        self.gridLayout_4.addWidget(self.stackedWidget_2, 1, 0, 1, 1)
        self.stackedWidget.addWidget(self.stranInformacije)
        self.nastavitve = QtWidgets.QWidget()
        self.nastavitve.setObjectName("nastavitve")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.nastavitve)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.gridLayout_8 = QtWidgets.QGridLayout()
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.label_5 = QtWidgets.QLabel(self.nastavitve)
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setFamily("Exo 2 Light")
        font.setPointSize(36)
        font.setItalic(False)
        font.setUnderline(False)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color:#828486;\n"
"")
        self.label_5.setObjectName("label_5")
        self.gridLayout_8.addWidget(self.label_5, 0, 0, 1, 1)
        self.gridLayout_9.addLayout(self.gridLayout_8, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.nastavitve)
        self.zacetnaStran = QtWidgets.QWidget()
        self.zacetnaStran.setObjectName("zacetnaStran")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.zacetnaStran)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.username = QtWidgets.QLineEdit(self.zacetnaStran)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.username.sizePolicy().hasHeightForWidth())
        self.username.setSizePolicy(sizePolicy)
        self.username.setMaximumSize(QtCore.QSize(300, 16777215))
        font = QtGui.QFont()
        font.setFamily("Exo 2")
        font.setPointSize(14)
        self.username.setFont(font)
        self.username.setStyleSheet("border: none;\n"
"background-color:#0CB1E8;\n"
"border-radius:10%;")
        self.username.setAlignment(QtCore.Qt.AlignCenter)
        self.username.setObjectName("username")
        self.gridLayout_12.addWidget(self.username, 2, 2, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.zacetnaStran)
        self.label_9.setMaximumSize(QtCore.QSize(320, 16777215))
        font = QtGui.QFont()
        font.setFamily("Exo 2")
        font.setPointSize(14)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("color:#828486;")
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout_12.addWidget(self.label_9, 2, 1, 1, 1)
        self.password = QtWidgets.QLineEdit(self.zacetnaStran)
        self.password.setMaximumSize(QtCore.QSize(300, 16777215))
        font = QtGui.QFont()
        font.setFamily("Exo 2")
        font.setPointSize(14)
        self.password.setFont(font)
        self.password.setStyleSheet("border: none;\n"
"background-color:#0CB1E8;\n"
"border-radius:10%;\n"
"color:#ffff;")
        self.password.setAlignment(QtCore.Qt.AlignCenter)
        self.password.setObjectName("password")
        self.gridLayout_12.addWidget(self.password, 3, 2, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.zacetnaStran)
        self.label_8.setMaximumSize(QtCore.QSize(320, 16777215))
        font = QtGui.QFont()
        font.setFamily("Exo 2")
        font.setPointSize(14)
        self.label_8.setFont(font)
        self.label_8.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_8.setStyleSheet("color:#828486;\n"
"margin-left:0;")
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout_12.addWidget(self.label_8, 3, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.zacetnaStran)
        self.label_4.setMaximumSize(QtCore.QSize(300, 75))
        font = QtGui.QFont()
        font.setFamily("Exo 2 Light")
        font.setPointSize(36)
        self.label_4.setFont(font)
        self.label_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_4.setStyleSheet("color:#828486;")
        self.label_4.setObjectName("label_4")
        self.gridLayout_12.addWidget(self.label_4, 0, 1, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.zacetnaStran)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_12.addWidget(self.pushButton, 0, 2, 1, 1)
        self.stackedWidget.addWidget(self.zacetnaStran)
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.page)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.gridLayoutRezerviraj = QtWidgets.QGridLayout()
        self.gridLayoutRezerviraj.setObjectName("gridLayoutRezerviraj")
        self.gridLayout_11.addLayout(self.gridLayoutRezerviraj, 1, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.page)
        self.label_6.setMaximumSize(QtCore.QSize(760, 50))
        font = QtGui.QFont()
        font.setFamily("Exo 2 Light")
        font.setPointSize(36)
        font.setItalic(False)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color:#828486;")
        self.label_6.setObjectName("label_6")
        self.gridLayout_11.addWidget(self.label_6, 0, 0, 1, 1)
        self.btn_nazaj3 = QtWidgets.QPushButton(self.page)
        self.btn_nazaj3.setMinimumSize(QtCore.QSize(30, 50))
        font = QtGui.QFont()
        font.setFamily("Exo 2")
        font.setPointSize(14)
        self.btn_nazaj3.setFont(font)
        self.btn_nazaj3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_nazaj3.setStyleSheet("background-color:#0CB1E8;\n"
"color: #ffffff;\n"
"border-radius:13%\n"
"")
        self.btn_nazaj3.setObjectName("btn_nazaj3")
        self.gridLayout_11.addWidget(self.btn_nazaj3, 2, 0, 1, 1)
        self.stackedWidget.addWidget(self.page)
        self.dateTimeLabel = QtWidgets.QLabel(self.centralwidget)
        self.dateTimeLabel.setGeometry(QtCore.QRect(36, 10, 721, 20))
        font = QtGui.QFont()
        font.setFamily("Monospac821 BT")
        font.setPointSize(12)
        self.dateTimeLabel.setFont(font)
        self.dateTimeLabel.setStyleSheet("color:#0CB1E8;")
        self.dateTimeLabel.setText("")
        self.dateTimeLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.dateTimeLabel.setObjectName("dateTimeLabel")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(3)
        self.stackedWidget_2.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "KoLJo"))
        self.kolo2niprisotno.setText(_translate("MainWindow", "Kolo 2 ni prisotno"))
        self.kolo1niprisotno.setText(_translate("MainWindow", "Kolo 1 ni prisotno"))
        self.btn_sposodi.setText(_translate("MainWindow", "I Z P O S O D I   S I"))
        self.btn_informacije.setText(_translate("MainWindow", "I N F O R M A C I J E"))
        self.kolo1prisotno.setText(_translate("MainWindow", "Kolo 1 prisotno"))
        self.kolo2prisotno.setText(_translate("MainWindow", "Kolo 2 prisotno"))
        self.polniKolo2.setText(_translate("MainWindow", "Polni kolo 2"))
        self.polniKolo1.setText(_translate("MainWindow", "Polni kolo 1"))
        self.btn_vrni.setText(_translate("MainWindow", "V R N I   K O L O"))
        self.btn_rezerviraj.setText(_translate("MainWindow", "R E Z E R V I R A J"))
        self.stebricek1rezerviran.setText(_translate("MainWindow", "Stebriček 1 rezerviran"))
        self.stebricek2rezerviran.setText(_translate("MainWindow", "Stebriček 2 rezerviran"))
        self.label.setText(_translate("MainWindow", "POSTAJA (ID POSTAJE)"))
        self.zeroBikes.setText(_translate("MainWindow", "TRENUTNO NI NA VOLJO NOBENEGA KOLESA"))
        self.btn_nazaj0.setText(_translate("MainWindow", "N A Z A J"))
        self.label_3.setText(_translate("MainWindow", "IZBERI POSTAJO rezervacija"))
        self.btn_nazaj2.setText(_translate("MainWindow", "N A Z A J"))
        self.btn_nazaj1.setText(_translate("MainWindow", "N A Z A J"))
        self.label_2.setText(_translate("MainWindow", "BLIŽNJE POSTAJE informacije"))
        self.btn_postaja1.setText(_translate("MainWindow", "Postaja 1"))
        self.btn_postaja4.setText(_translate("MainWindow", "Postaja 4"))
        self.btn_postaja3.setText(_translate("MainWindow", "Postaja 3"))
        self.btn_postaja2.setText(_translate("MainWindow", "Postaja 2"))
        self.label_5.setText(_translate("MainWindow", "NASTAVITVE"))
        self.label_9.setText(_translate("MainWindow", "U  P  O  R  A  B  N  I  Š  K  O     I  M  E :"))
        self.label_8.setText(_translate("MainWindow", "G  E  S  L  O :"))
        self.label_4.setText(_translate("MainWindow", "PRIJAVI SE"))
        self.pushButton.setText(_translate("MainWindow", "PushButton"))
        self.label_6.setText(_translate("MainWindow", "REZERVIRAJ STEBRIČEK"))
        self.btn_nazaj3.setText(_translate("MainWindow", "N A Z A J"))


